First Things First

In [1]:
print("Hello World!")

Hello World!


Data Types

In [37]:
i = 3
f = 3.5
s = "string"
b = True

print(type(i))
print(type(f))
print(type(s))
print(type(b))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


Operators

In [38]:
print(2 ** 3) # Exponentiation
print(97 // 10) # Floor Division
print(27 % 6) # Modulo

print("\n")

print(1 == 1) # True
print(True > False) # True
print(5 != False) # True

print("\n")

print(3 + 3)
print("3" + "3")
#print("3" + 3) Error: can only concatenate same data types
print("3" + str(3))


8
9
3


True
True
True


6
33
33


Conditional Logic and Loops

In [4]:
# Conditional Logic
x = 45.5
if (x < 33):
    print("Fail")
elif (x < 50):
    print("Okay")
else:
    print("Good")

print("\n")    

# While Loop
y = 5
while (y > 0):
    print(y)
    y = y - 1

print("\n")    

y = 5
while (y > 0):
    y = y - 1
    print(y)

print("\n")    

# For Loop
my_list = [13, 17, 21, 29]
for i in my_list:  # For each element in sequence
    print(i)


Okay


5
4
3
2
1


4
3
2
1
0


13
17
21
29


Functions and Methods

In [5]:
# Round
print(round(1.68)) # Default argument is 0
print(round(1.68, 1))

2
1.7


Lists

In [4]:
my_list = [1,8,27,64,125]

print(my_list[0]) # Index starts from 0
print(my_list[-1]) # Accessing Last Element

print("\n")

print(my_list) # All elements
print(my_list[:]) # All elements - No difference in output
print(my_list[0:]) # All elements
print(my_list[0:2]) # First index included Last index not included
print(my_list[:2]) # Same as above
print(my_list[2:]) # 2nd and beyond

print("\n")

print(my_list)
my_list[0] = 0 # Update element
print(my_list)

my_list = my_list + [216] # Add element
print(my_list)

del(my_list[-1]) # Delete Last Element
print(my_list)
del my_list[-1] # Alternate syntax
print(my_list)

print("\n")

my_new_list = my_list
my_new_list[0] = 1
print(my_new_list)
print(my_list) # Old List is also affected
my_new_list_2 = list(my_new_list) # Use this or my_new_list_2 = my_new_list(:)

print("\n")
funk = [1 + 2, "a" * 5, 3] # Funky Feature - Operations on the Go
print(funk) # A is printed 5 times

1
125


[1, 8, 27, 64, 125]
[1, 8, 27, 64, 125]
[1, 8, 27, 64, 125]
[1, 8]
[1, 8]
[27, 64, 125]


[1, 8, 27, 64, 125]
[0, 8, 27, 64, 125]
[0, 8, 27, 64, 125, 216]
[0, 8, 27, 64, 125]
[0, 8, 27, 64]


[1, 8, 27, 64]
[1, 8, 27, 64]


[3, 'aaaaa', 3]


Dictionaries

In [1]:
pricing = {"model_a":500000 , "model_b":400000, "model_c":350000}
print(pricing)
print("\n")

print(pricing['model_a']) # Printing an element
pricing['model_b'] = 450000 # Updating an element
print(pricing)
print("\n")

del(pricing['model_a']) # Deleting an element
print(pricing)


{'model_a': 500000, 'model_b': 400000, 'model_c': 350000}


500000
{'model_a': 500000, 'model_b': 450000, 'model_c': 350000}


{'model_b': 450000, 'model_c': 350000}
Variable   Type    Data/Info
----------------------------
pricing    dict    n=2


In [3]:
%whos # To view the variables in the environment

No variables match your requested type.


NumPy

In [21]:
import numpy as np

my_marks_list = [79,80,85,90,70]
my_marks_arr = np.array([79,80,85,90,70])
print(my_marks_list) 
print(type(my_marks_list)) # list
print(my_marks_arr)
print(type(my_marks_arr)) # numpy.ndarray

print("\n")


a_plus = my_marks_arr > 80
print(a_plus)

a_plus_list = my_marks_arr[a_plus]
print(a_plus_list)
a_plus_list_easy = my_marks_arr[my_marks_arr>80] # Alternative
print(a_plus_list_easy)


print("\n")

my_marks_list = my_marks_list + [50]
my_marks_arr = my_marks_arr + 50
print(my_marks_list)
print(my_marks_arr)

print("\n")


my_2d_array = np.array([[1,2,3,4],[1,4,9,16]])
print(my_2d_array)
print(type(my_2d_array))
print(my_2d_array.shape) # rows, column

print("\n")

# Accessing elements
print(my_2d_array[0][1])
print(my_2d_array[0,1])

print("\n")

# Adding elements
init_list = np.array([1,2,3])
init_list_1 = init_list + 1 # Adds one to each elements
init_list_2 = init_list + np.array([1]) # Same
init_list_3 = np.append(init_list,np.array([1])) # Append

print(init_list)
print(init_list_1)
print(init_list_2)
print(init_list_3)

[79, 80, 85, 90, 70]
<class 'list'>
[79 80 85 90 70]
<class 'numpy.ndarray'>


[False False  True  True False]
[85 90]
[85 90]


[79, 80, 85, 90, 70, 50]
[129 130 135 140 120]


[[ 1  2  3  4]
 [ 1  4  9 16]]
<class 'numpy.ndarray'>
(2, 4)


2
2


[1 2 3]
[2 3 4]
[2 3 4]
[1 2 3 1]


Pandas and Dataframes

In [17]:
import pandas as pd

s_no = [1,2,3,4]
country = ["United States", "Brazil", "India", "Russia"]
cases = [1.9, 1, 0.8, 0.6]

df_dict = {"S_no":s_no, "Country":country, "Cases":cases}
print(df_dict)

df = pd.DataFrame(df_dict)
print(df) # Row Indexes are Created Automatically

# Alternative
df_2 = pd.DataFrame(
    {
    's_no' : [1,2,3,4],
    'country' : ["United States", "Brazil", "India", "Russia"],
    'cases' : [1.9, 1, 0.8, 0.6]
    }
)

print("\n")

# Assign Row Index
df.index = ["USA", "BRA", "IND", "RUS"]
print(df)


print("\n")

# Subsetting Data
print(df[0:2]) # Selecting Rows. Default Return Type is Pandas DataFrame
print("\n")
print(type(df["Country"])) # Selecting Columns. Default Return Type is Pandas Series. More Columns can't be Selected
print(type(df[["Country", "Cases"]])) # Selecting Columns and Returning Pandas DataFrame
print("\n")

print(df.loc["USA"]) # Selecting Rows using loc. Default output isn't a DF. Use Double Square Brackets for DF
print("\n")
print(df.loc[["USA", "IND"],["Country", "Cases"]]) # Output as DF by using double brackets
print("\n")
print(df.iloc[[0,2],[1, 2]]) # Same result using iloc - DF Index isn't included in column numbering
print("\n")

# Fitlering Data
print(df.loc[df.Cases>=1])





{'S_no': [1, 2, 3, 4], 'Country': ['United States', 'Brazil', 'India', 'Russia'], 'Cases': [1.9, 1, 0.8, 0.6]}
   S_no        Country  Cases
0     1  United States    1.9
1     2         Brazil    1.0
2     3          India    0.8
3     4         Russia    0.6


     S_no        Country  Cases
USA     1  United States    1.9
BRA     2         Brazil    1.0
IND     3          India    0.8
RUS     4         Russia    0.6


     S_no        Country  Cases
USA     1  United States    1.9
BRA     2         Brazil    1.0


<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


S_no                   1
Country    United States
Cases                1.9
Name: USA, dtype: object


Country    United States
Cases                1.9
Name: USA, dtype: object


           Country  Cases
USA  United States    1.9
IND          India    0.8


           Country  Cases
USA  United States    1.9
IND          India    0.8


     S_no        Country  Cases
USA     1  United States    1.

In [35]:
%whos

Variable        Type         Data/Info
--------------------------------------
cases           list         n=4
country         list         n=4
data            ndarray      3x5: 15 elems, type `int32`, 60 bytes
df              DataFrame         s_no        country <...>   4         Russia   0.6
df_dict         dict         n=3
my_2d_array     ndarray      2x4: 8 elems, type `int32`, 32 bytes
my_marks        ndarray      5: 5 elems, type `int32`, 20 bytes
my_marks_arr    ndarray      5: 5 elems, type `int32`, 20 bytes
my_marks_list   list         n=6
np              module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pd              module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
s_no            list         n=4
