First Things First

In [1]:
print("Hello World!")

Hello World!


Data Types

In [2]:
i = 1
f = 3.5
s = "hey"
b = True

print(type(i))
print(type(f))
print(type(s))
print(type(b))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


Operators

In [3]:
print(2 ** 3) # Exponentiation
print(97 // 10) # Floor Division
print(27 % 6) # Modulo

print("\n")

print(1 == 1) # True
print(True > False) # True
print(5 != False) # True

print("\n")

print(3 + 3)
print("3" + "3")
#print("3" + 3) Error: can only concatenate same data types
print("3" + str(3))


8
9
3


True
True
True


6
33
33


Conditional Logic and Loops

In [4]:
# Conditional Logic
x = 45.5
if (x < 33):
    print("Fail")
elif (x < 50):
    print("Okay")
else:
    print("Good")

print("\n")    

# While Loop
y = 5
while (y > 0):
    print(y)
    y = y - 1

print("\n")    

y = 5
while (y > 0):
    y = y - 1
    print(y)

print("\n")    

# For Loop
my_list = [13, 17, 21, 29]
for i in my_list:  # For each element in sequence
    print(i)


Okay


5
4
3
2
1


4
3
2
1
0


13
17
21
29


Functions and Methods

In [5]:
# Round
print(round(1.68)) # Default argument is 0
print(round(1.68, 1))

2
1.7


Lists

In [6]:
my_list = [1,8,27,64,125]

print(my_list[0]) # Index starts from 0
print(my_list[-1]) # Accessing Last Element

print("\n")

print(my_list) # All elements
print(my_list[:]) # All elements - No difference in output
print(my_list[0:]) # All elements
print(my_list[0:2]) # First index included Last index not included
print(my_list[:2]) # Same as above
print(my_list[2:]) # 2nd and beyond

print("\n")

print(my_list)
my_list[0] = 0 # Update element
print(my_list)

my_list = my_list + [216] # Add element
print(my_list)

del(my_list[-1]) # Delete Last Element
print(my_list)
del my_list[-1] # Alternate syntax
print(my_list)

print("\n")

my_new_list = my_list
my_new_list[0] = 1
print(my_new_list)
print(my_list) # Old List is also affected
my_new_list_copy = list(my_new_list) # Use this or my_new_list_copy = my_new_list(:)

print("\n")
five_a = [1 + 2, "a" * 5, 3]
print(five_a) # A is printed 5 times

1
125


[1, 8, 27, 64, 125]
[1, 8, 27, 64, 125]
[1, 8, 27, 64, 125]
[1, 8]
[1, 8]
[27, 64, 125]


[1, 8, 27, 64, 125]
[0, 8, 27, 64, 125]
[0, 8, 27, 64, 125, 216]
[0, 8, 27, 64, 125]
[0, 8, 27, 64]


[1, 8, 27, 64]
[1, 8, 27, 64]


[3, 'aaaaa', 3]


Dictionaries

In [7]:
pricing = {"model_a":500000 , "model_b":400000, "model_c":350000}
print(pricing)
print("\n")

print(pricing['model_a']) # Printing an element
pricing['model_b'] = 450000 # Updating an element
print(pricing)
print("\n")

del(pricing['model_a']) # Deleting an element
print(pricing)


{'model_a': 500000, 'model_b': 400000, 'model_c': 350000}


500000
{'model_a': 500000, 'model_b': 450000, 'model_c': 350000}


{'model_b': 450000, 'model_c': 350000}


In [8]:
%whos # To view the variables in the environment

No variables match your requested type.


NumPy

In [9]:
import numpy as np

my_marks_list = [79,80,85,90,70]
my_marks_arr = np.array([79,80,85,90,70])
print(my_marks_list) 
print(type(my_marks_list)) # list
print(my_marks_arr)
print(type(my_marks_arr)) # numpy.ndarray

print("\n")

my_marks_list = my_marks_list + [50] # adds 50 in the list
my_marks_arr = my_marks_arr + 50 # add 50 to each element
print(my_marks_list)
print(my_marks_arr)

print("\n")


# Appending elements
init_list = np.array([1,2,3])
init_list_1 = init_list + 10 # Adds one to each elements
init_list_2 = init_list + np.array([10]) # Same
init_list_3 = np.append(init_list,np.array([10])) # Append

print(init_list)
print(init_list_1)
print(init_list_2)
print(init_list_3)

print("\n")

my_2d_array = np.array([[1,2,3,4],[1,4,9,16]])
print(my_2d_array)
print(type(my_2d_array))
print(my_2d_array.shape) # rows, column

print("\n")

# Accessing elements
print(my_2d_array[0][1])
print(my_2d_array[0,1])

print("\n")


# Filtering Elements
a_plus = my_marks_arr > 120
print(a_plus)

a_plus_list = my_marks_arr[a_plus]
print(a_plus_list)
a_plus_list_easy = my_marks_arr[my_marks_arr>120] # Alternative
print(a_plus_list_easy)



[79, 80, 85, 90, 70]
<class 'list'>
[79 80 85 90 70]
<class 'numpy.ndarray'>


[79, 80, 85, 90, 70, 50]
[129 130 135 140 120]


[1 2 3]
[11 12 13]
[11 12 13]
[ 1  2  3 10]


[[ 1  2  3  4]
 [ 1  4  9 16]]
<class 'numpy.ndarray'>
(2, 4)


2
2


[ True  True  True  True False]
[129 130 135 140]
[129 130 135 140]


Pandas and Dataframes

In [10]:
# Creating DataFrames

import pandas as pd

s_no = [1,2,3,4]
country = ["United States", "Brazil", "India", "Russia"]
cases = [1.9, 1, 0.8, 0.6]

df_dict = {"S_no":s_no, "Country":country, "Cases":cases}
print(df_dict)

df = pd.DataFrame(df_dict)
print(df) # Row Indexes are Created Automatically

# Alternative
df_2 = pd.DataFrame(
    {
    's_no' : [1,2,3,4],
    'country' : ["United States", "Brazil", "India", "Russia"],
    'cases' : [1.9, 1, 0.8, 0.6]
    }
)

{'S_no': [1, 2, 3, 4], 'Country': ['United States', 'Brazil', 'India', 'Russia'], 'Cases': [1.9, 1, 0.8, 0.6]}
   S_no        Country  Cases
0     1  United States    1.9
1     2         Brazil    1.0
2     3          India    0.8
3     4         Russia    0.6


In [11]:
# Assign Row Index
df.index = ["USA", "BRA", "IND", "RUS"]
print(df)

     S_no        Country  Cases
USA     1  United States    1.9
BRA     2         Brazil    1.0
IND     3          India    0.8
RUS     4         Russia    0.6


In [12]:
# Exploring Data
print(df.info()) # Info Method
print(df.describe()) # Describe Method
print(df.shape) # Not a Method, but an Attribute
print(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, USA to RUS
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   S_no     4 non-null      int64  
 1   Country  4 non-null      object 
 2   Cases    4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 128.0+ bytes
None
           S_no    Cases
count  4.000000  4.00000
mean   2.500000  1.07500
std    1.290994  0.57373
min    1.000000  0.60000
25%    1.750000  0.75000
50%    2.500000  0.90000
75%    3.250000  1.22500
max    4.000000  1.90000
(4, 3)
     S_no        Country  Cases
USA     1  United States    1.9
BRA     2         Brazil    1.0
IND     3          India    0.8
RUS     4         Russia    0.6


In [13]:
# Components - Values, Columns and Index
df.values


array([[1, 'United States', 1.9],
       [2, 'Brazil', 1.0],
       [3, 'India', 0.8],
       [4, 'Russia', 0.6]], dtype=object)

In [14]:
df.columns


Index(['S_no', 'Country', 'Cases'], dtype='object')

In [15]:
df.index

Index(['USA', 'BRA', 'IND', 'RUS'], dtype='object')

In [16]:
# Sorting Data
#df.sort_values("Cases") # Ascending by Default
df.sort_values("Cases", ascending = False) # Use ascending = [True,False]) for Multi-Level Sort


S_no        Country  Cases
USA     1  United States    1.9
BRA     2         Brazil    1.0
IND     3          India    0.8
RUS     4         Russia    0.6

In [17]:
# Filtering Rows/Columns
print(df[0:2]) # Filtering Rows. Default Return Type is Pandas DataFrame
print("\n")
print(type(df["Country"])) # Selecting Columns. Default Return Type is Pandas Series. More than one Columns can't be Selected!
print(type(df[["Country", "Cases"]])) # Selecting Multiple Columns and Returning Pandas DataFrame
print(df[["Country", "Cases"]])
print("\n")

     S_no        Country  Cases
USA     1  United States    1.9
BRA     2         Brazil    1.0


<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
           Country  Cases
USA  United States    1.9
BRA         Brazil    1.0
IND          India    0.8
RUS         Russia    0.6




In [18]:
# Filtering Data Based on Conditions
print(df[df["Cases"]>=1]) # Subsetting Rows wrt a Condition

print(df[(df["Cases"]>=1) & (df["S_no"] >= 2)]) # Multiple Conditions


     S_no        Country  Cases
USA     1  United States    1.9
BRA     2         Brazil    1.0
     S_no Country  Cases
BRA     2  Brazil    1.0


In [19]:
# Is In Method - Multiple Filters
print(df[df["Country"].isin(["United States", "India"])])

     S_no        Country  Cases
USA     1  United States    1.9
IND     3          India    0.8


In [20]:
# loc and iloc
print(df.loc["USA"]) # Selecting Rows using loc. Default output isn't a DF. Use Double Square Brackets for DF
print("\n")
print(df.loc[["USA", "IND"],["Country", "Cases"]]) # Output as DF by using double brackets
print("\n")
print(df.iloc[[0,2],[1, 2]]) # Same result using iloc - DF Index isn't included in column numbering
print("\n")


S_no                   1
Country    United States
Cases                1.9
Name: USA, dtype: object


           Country  Cases
USA  United States    1.9
IND          India    0.8


           Country  Cases
USA  United States    1.9
IND          India    0.8




In [21]:
# Creating Columns
df["Cases_Exact"] = df["Cases"] * 1000000
print(df)

     S_no        Country  Cases  Cases_Exact
USA     1  United States    1.9    1900000.0
BRA     2         Brazil    1.0    1000000.0
IND     3          India    0.8     800000.0
RUS     4         Russia    0.6     600000.0


In [22]:
# Renaming Columns
df.columns = ['s_no','country','cases_mn', 'cases_exact']

In [24]:
# Summary Statistics
print(df["cases_exact"].mean())


1075000.0


In [25]:
# Summary by Categorical Variables
df["Location"] = ["West", "West", "East", "East"]
print(df.head())

# Value Counts
print(df["Location"].value_counts())
print(df["Location"].value_counts(sort = True)) # Sorting
print(df["Location"].value_counts(normalize = True)) # Proportion

# Group By
print(df.groupby("Location")["cases_exct"].sum())

# Pivot Table
print(df.pivot_table(values = "case_exact", index = "Location",
                     columns = "Country", aggfunc = np.sum, 
                     fill_value = 0, margins = True)) # By default Calculate the Mean

     s_no        country  cases_mn  cases_exact Location
USA     1  United States       1.9    1900000.0     West
BRA     2         Brazil       1.0    1000000.0     West
IND     3          India       0.8     800000.0     East
RUS     4         Russia       0.6     600000.0     East
West    2
East    2
Name: Location, dtype: int64
West    2
East    2
Name: Location, dtype: int64
West    0.5
East    0.5
Name: Location, dtype: float64


KeyError: 'Column not found: cases_exct'